### ISSUE TITLE
Foreman branching release owner improvements

### ISSUE THREAD

**Issue by Griffin-Sullivan** [theforeman/theforeman-rel-eng#393]
Would like to track a few branching issues I've encountered:

- [ ] #312
    * This step should rebase and release owners need push rights. Since I don't have push rights, I have to open separate PRs for everything except foreman-selinux since it doesn't have push protection
- [ ] #399
    * This needs to be more descriptive and should mention that code updates are required for each of the deprecations for anything <= X.Y. Link should take you to [Code search results · GitHub](https://github.com/search?q=repo%3Atheforeman%2Fforeman%20Foreman%3A%3ADeprecation.deprecation_warning&type=code)
- [x] [Create Redmine version x.y.0 and make sure it is shared with subprojects in foreman](https://github.com/theforeman/theforeman-rel-eng/pull/390)
    * This step needs to be moved to right after develop branch bump

**Comment by ekohl** [comment]
> * This step needs to be moved to right after develop branch bump

Wasn't this done in https://github.com/theforeman/theforeman-rel-eng/commit/92b2650cc304a653ddc3f3fc7ee3fab980d7834e?

**Comment by ekohl** [comment]
I split this up into separate issues so it's easier to tackle.
